
import os
from pathlib import Path

def list_files():

    return os.listdir(".")

def read_file(path="README.md"):

    p = Path(path)

    if not p.exists():

        return f"File not found: {path}"

    return p.read_text()[:4000]

def search_codebase():

    matches = []

    for path in Path(".").rglob("*.py"):

        try:

            text = path.read_text()

            if "Runtime" in text or "Tool" in text:

                matches.append(str(path))

        except:
            pass

    return matches

def write_file():

    Path("agent_notes.txt").write_text(
        "Generated by Mini Claw Runtime v5"
    )

    return "Created agent_notes.txt"

def run_python():

    code = "print(sum(range(100)))"

    namespace = {}

    exec(code, namespace)

    return "Executed python snippet"

def inspect_architecture():

    return {
        "runtime": "runtime/conversation_runtime.py",
        "tools": "tools/router.py",
        "memory": "memory/retrieval.py",
        "models": "models/ollama_client.py",
        "tasks": "tasks/task_queue.py"
    }

def grep_text():

    results = []

    for path in Path(".").rglob("*.py"):

        try:

            text = path.read_text()

            if "tool" in text.lower():

                results.append(str(path))

        except:
            pass

    return results
