import os
from pathlib import Path

def list_files():
    return os.listdir(".")

def read_file():

    path = Path("README.md")

    if not path.exists():
        return "README.md not found"

    return path.read_text()[:3000]

def search_codebase():

    matches = []

    for path in Path(".").rglob("*.py"):

        text = path.read_text()

        if "Runtime" in text or "Tool" in text:

            matches.append(str(path))

    return matches

def write_file():

    Path("agent_notes.txt").write_text(
        "Generated by Mini Claw Runtime"
    )

    return "Created agent_notes.txt"

def run_python():

    code = "print(sum(range(100)))"

    namespace = {}

    exec(code, namespace)

    return "Executed python snippet"

def inspect_architecture():

    return {
        "runtime": "runtime/conversation_runtime.py",
        "tools": "tools/router.py",
        "memory": "memory/retrieval.py",
        "models": "models/ollama_client.py"
    }

def grep_text():

    results = []

    for path in Path(".").rglob("*.py"):

        text = path.read_text()

        if "tool" in text.lower():

            results.append(str(path))

    return results
